### PR TITLE
Optimizations for AMD Bulldozer

### PR DESCRIPTION
**Pull request by SChernykh**
- Added support for XOP instructions
- Enabled Ryzen code for Bulldozer because it's faster there too

### CODE REVIEW

**Comment by UnclWish** [comment]
Tried dev version with buldozer optimizations...
loki algo
xmrig 5.5.1 - 1 core from FX 8320 - 350-385 h/s
xmrig dev - 1 core from FX 8320 - 250-285 h/s

**Comment by SChernykh** [comment]
Can you try to set `"wrmsr":false` in config and compare again? Also please double check that xmrig allocates 100% huge pages every time and nothing else is running during hashrate tests.

**Comment by UnclWish** [comment]
With "wrmsr":false and restarting miner speed became about 350+ h/s - normal.
Without restarting with reloading config on the fly nothing changes. MSR reloads only with full miner restart.
And with "wrmsr":true speed 250 h/s.

**Comment by SChernykh** [comment]
It seems that MSR values that worked for Piledriver don't work for Bulldozer (I tested it on Opteron 6338P). Too bad, I hoped it would be the same.

**Comment by UnclWish** [comment]
Maybe MSR values for Buldozer are differs?

**Comment by UnclWish** [comment]
Sorry for offtop: you're russian?

**Comment by SChernykh** [comment]
Yes.

**Comment by UnclWish** [comment]
Can we speak on russian language here? )))

**Comment by Lonnegan** [comment]
May be the optimization works for the original bulldozer (e.g. FX-8150), but with piledriver (e.g. FX-8350) version 5.1.1 is faster, 1330 H/s vs. 1300 H/s. Not much difference, but reproducible.

**Comment by SChernykh** [comment]
@Lonnegan Can you try to set "asm" to false in config.json and test 5.5.3 again? This will turn off AMD-specific optimizations.

**Comment by SChernykh** [comment]
@Lonnegan I've been told that someone else with AMD FX-8320E (which is also Piledriver) got better hashrate on 5.5.3 - it went up from 2300 to 2313 h/s. So maybe there is something interfering with mining on your PC.

**Comment by Lonnegan** [comment]
I'll try tonight.

**Comment by Lonnegan** [comment]
Ok, it was my fault! I compared 5.5.1-msvc vs. 5.5.3-gcc by accident. 5.5.3-msvc is indeed about 20 H/s faster even on Piledriver based CPU! :) Good job!

**Pull request merged**
