### PR TITLE
Support for solo mining with miner signatures (Wownero)

### PR DESCRIPTION
**Pull request by SChernykh**
CPU only for now because elliptic curve operations are required for mining.

To test:
- Compile https://git.wownero.com/wownero/wownero/src/branch/dev-v0.10
- start `wownerod --testnet --offline --fixed-difficulty 10000`
- wownerod --start-mining ADDRESS --spendkey SPENDKEY
- wait until it mines past block height 60
- `stop_mining` in wownerod
- run `xmrig -o 127.0.0.1:11181 --coin wownero -u ADDRESS --spend-secret-key SPENDKEY --daemon`

### CODE REVIEW

**Comment by peme14k** [comment]
#2445SChernykh:miner_signature

**Comment by kl1059** [comment]
I suggest adding 
--spend-secret-key-from-file filename
its always been bad practice to put passwords etc in the command line argument on linux because of the 'ps axw' command, image accounting, or system crash dumps that contain all the commands running with their args.  Someone could upload a kernel crash dump to their favorite distro support team and disclose their spendkey (which i am guessing is bad).

admittedly most linux systems are single user systems now so the risk is low

**Comment by SChernykh** [comment]
There's a `config.json` file for this, command line parameters are just duplicates of what's available there.

**Comment by Valenzuelafer** [comment]
Need help

**Review by Valenzuelafer — COMMENTED** [review]
Monero.mine

**Pull request merged**
