### PR TITLE
work as service 

### PR DESCRIPTION
**Pull request by ShaddyR**
So, work_as_service for windows was realized?
Or can you modify pause-on-active mechanism or add other variant for multiuser system like server RDP? To watch if any session is active and pause waiting while all are deactivated? As variant - something like "green mode" - minimalistic cpu threads (configurable) and priority (cpu time) using if there are any active user sessions.

### CODE REVIEW

**Comment by Titaniumtown** [comment]
What?

**Comment by ShaddyR** [comment]
> What?
That! )

**Comment by Titaniumtown** [comment]
why did you make a pull request?

**Comment by ShaddyR** [comment]
> why did you make a pull request?

what's wrong? I tried to ask for  another  feature for the soft. Where is my mistake?

**Comment by Titaniumtown** [comment]
You made a pull request lol.

**Comment by ShaddyR** [comment]
Ok. I don't understand structure of the site. Where do i have to ask for the feature?

**Comment by Spudz76** [comment]
Pull Requests are for when you already wrote the feature and want to merge it for everyone to use.  It's a Request for the maintainer to Pull your changes into the mix.  In GitLab they are called Merge Requests which may or may not be less confusing.

Issues are how you ask questions, whether for support, or for feature requests.

But also use search because this has been asked before, and if I recall correctly, denied.  Be sure to search "closed" issues too (not just 'is:open' as the default search does).

**Comment by ShaddyR** [comment]
> Pull Requests are for when you already wrote the feature and want to merge it for everyone to use. It's a Request for the maintainer to Pull your changes into the mix. In GitLab they are called Merge Requests which may or may not be less confusing.
> 
> Issues are how you ask questions, whether for support, or for feature requests.
> 
> But also use search because this has been asked before, and if I recall correctly, denied. Be sure to search "closed" issues too (not just 'is:open' as the default search does).

thanks a lot. I found request like my but don't see it's status  "closed" . Well it isn't so imortant so can anybody delete my post?

**Comment by Titaniumtown** [comment]
dude, close this PR. jesus

**Pull request closed without merging**
