### PR TITLE
Added support for Uplexa (cn/upx2 algorithm)

### PR DESCRIPTION
**Pull request by SChernykh**

### CODE REVIEW

**Comment by SChernykh** [comment]
Bonus: MSVC version for Windows is faster than other miners by 3-4% on Ryzen CPUs.

**Comment by SChernykh** [comment]
Update: https://github.com/xmrig/xmrig/pull/2278 - GCC version is a bit faster than MSVC now. This code is now the fastest on Zen3 with big margin (**7.8%** faster than SRBMiner, **15.7%** faster than XMRigCC on my **Ryzen 5 5600X**).

**Comment by Lonnegan** [comment]
Interesting fact: on Zen 1+ (2700) the configuration ...

     "cn/upx2": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7],
            [1, 8],
            [1, 9],
            [1, 10],
            [1, 11],
            [1, 12],
            [1, 13],
            [1, 14],
            [1, 15]
        ],

...is faster than the default config...

     "cn/upx2": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5],
            [2, 6],
            [2, 7],
            [2, 8],
            [2, 9],
            [2, 10],
            [2, 11],
            [2, 12],
            [2, 13],
            [2, 14],
            [2, 15]
        ],

Not much, but reproducable 43 kH/s vs. 42 hH/s.

**Comment by ariegrossman** [comment]
still slower than srbminer on intel.

**Comment by Lonnegan** [comment]
I've tested the MSVC version of 6.12.0 in UPX. It throws errors:
Screenshot 2021-04-21 115034
XHV and XMR are working fine. It's a prime-stable Ryzen 7 5800X. Perhaps a problem with the special asm for Zen 3?

**Comment by SChernykh** [comment]
Yes, it's something with Zen3 asm code, I'll check it.

**Comment by Lonnegan** [comment]
Yes, it's the same with GCC. Countertest with asm false

**Comment by SChernykh** [comment]
Fix: https://github.com/xmrig/xmrig/pull/2296

**Pull request merged**
