### PR TITLE
New MSR mod for Ryzen

### PR DESCRIPTION
**Pull request by SChernykh**
+3.5% on Zen2, +1-2% on Zen3

### CODE REVIEW

**Comment by xmrig** [comment]
https://download.xmrig.com/xmrig/6.5.1-dev/5df1686810dd568906c47d55f69ea82fe7193926/ user `xmrig` password `download` binaries for testing.

**Comment by Lonnegan** [comment]
I've tested it on an AMD Ryzen 9 3900X; no measurable difference between 6.3.5 and 6.5.1. Are those +3,5% on Zen 2 OS specific? I've tested Windows Server 2019.

**Comment by SChernykh** [comment]
@Lonnegan What's your RAM speed and timings? Multiple people tested it and got performance increase.

**Comment by Lonnegan** [comment]
@SChernykh 2x 32 GB DDR4-2667 unbuffered ECC in dual channel mode. Binaries were the MSVC ones. I'll try the GCC ones and Win 10 instead of Server 2019.

**Pull request merged**
