### PR TITLE
Stratum mode self-select

### PR DESCRIPTION
**Pull request by jtgrassie**
Info: https://github.com/jtgrassie/monero-pool/blob/master/stratum-ss.md

### CODE REVIEW

**Comment by trasherdk** [comment]
Any chance of getting this one into release, soon?

**Comment by xmrig** [comment]
Any public pools available?
Thank you.

**Comment by trasherdk** [comment]
This feature was recently merged into [monero (master) ](https://github.com/monero-project/monero/pull/5728https://github.com/monero-project/monero/pull/5728)

[monero-pool on githup](https://github.com/jtgrassie/monero-pool)
[xmrig with stratum-ss on github](https://github.com/jtgrassie/xmrig)

[testnet pool](http://ghost-m1.fumlersoft.dk:8001/)
[mainnet pool](http://monerop.com/)

**Comment by jtgrassie** [comment]
@xmrig let me know (email/IRC/here) if there is anything you want changing to merge this in. Right now I'm in a holding pattern rebasing to master each time you do a release.

**Comment by trasherdk** [comment]
PING!

**Comment by xmrig** [comment]
There some NUMA/hugepages related changes pending for v4, once it done (likely in next v4.3 release) I will review this pull request. Sorry for delay.
Thank you.

**Comment by trasherdk** [comment]
Working good in Evo branch.
Thanks.

**Comment by xmrig** [comment]
v4.4.0-beta with this feature released.
Thank you.

**Comment by trasherdk** [comment]
Yep, got it. Test ran without any hick-ups.

**Pull request closed without merging**
