### PR TITLE
Possibile performance improvements

### PR DESCRIPTION
**Pull request by aegroto**
Hello everyone,

I tried latest releases of xmrig on both ARM and x86 and i found out that they give really good performances compared to other miners, congratulations to whoever worked and/or contributed to the code.

As a self-teaching optimization exercise I decided to take a look at XMRig's code and to write little patches that should improve hashrate.

I don't want this PR to be necessarily fully merged (it may not be merged at all), but I'd like to have a feedback by everyone watching this repository and hopefully to help this project grow.

I'll commit every modification I make at the original application on my fork, so this PR will be constantly updated with all the job I made.

### CODE REVIEW

**Comment by xmrig** [comment]
I don't see any noticeable hashrate difference, anyway whole explode/implode is smaller part of hash time. Also please use dev branch.
Thank you.

**Comment by sahaab** [comment]
Hey, sorry to go off topic here, were you able to get the miner built and worming on arm 32bit? (armv7)

**Comment by aegroto** [comment]
@sahaab Yes, i did nothing but compile it as i was in a x86 processor, but as you said that's off topic.

@xmrig Ok, sorry, i'll reopen this PR on the dev branch.

**Comment by sahaab** [comment]
@aegroto i am sorry but could you help me achieve this?? 
My compile build from ndk was working, but it was extremely slower than a build from using a armv7 phone, but when I compile from a phone, I get some compiling errors on phone and a bus error when running.

**Comment by aegroto** [comment]
@sahaab I'm sorry, I just compiled on an ARM GNU/Linux distribution, not on a phone.
If you need further help, please crete an issue.

**Pull request closed without merging**
