### PR TITLE
Add -DBUILD_STATIC=ON for static builds

### PR DESCRIPTION
**Pull request by kpcyrd**
See #238

### CODE REVIEW

**Comment by xmrig** [comment]
It not solve the issue, fully static binary is much more complicated, check this comment https://github.com/xmrig/xmrig/issues/238#issuecomment-353468507
Thank you.

**Comment by kpcyrd** [comment]
@xmrig this is true, it makes the process in https://github.com/xmrig/xmrig/issues/238#issuecomment-354468976 simpler though. Instead of doing:
```
sed '/add_executable/iset(CMAKE_EXE_LINKER_FLAGS " -static")' -i ../CMakeLists.txt
cmake .. -DMHD_INCLUDE_DIR=${mhdpath}/src/include -DMHD_LIBRARY=/${mhdpath}/src/microhttpd/.libs/libmicrohttpd.a
```
you would just do:
```
cmake .. -DBUILD_STATIC=ON -DMHD_INCLUDE_DIR=${mhdpath}/src/include -DMHD_LIBRARY=/${mhdpath}/src/microhttpd/.libs/libmicrohttpd.a
```

If you're building in an alpine container this is sufficient to build a static binary:
```
git clone --depth=1 https://github.com/xmrig/xmrig
mkdir xmrig/build && cd xmrig/build
cmake .. -DWITH_HTTPD=OFF -DBUILD_STATIC=ON
make
```

**Comment by xmrig** [comment]
Okay, I will merge it later, after merging dev branch into master.
Thank you.

**Comment by kpcyrd** [comment]
It seems there was a problem with the merge. My commit (11f00a2) is able to build a static binary, while the merge commit (fdc9fbe) is not.

11f00a2:
```
	ldd (0x65db7a6eb000)
```

fdc9fbe:
```
	ldd (0x6808fb97e000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x6808fb3aa000)
	libc.musl-x86_64.so.1 => ldd (0x6808fb97e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x6808fb198000)
```

I've tracked this down by diffing those two commits and found a change in `cmake/FindUV.make` that seems to be the problem. I'm able to build a static binary with the merge commit after applying this patch:
```
diff --git a/cmake/FindUV.cmake b/cmake/FindUV.cmake
index 7906633..e3c22d2 100644
--- a/cmake/FindUV.cmake
+++ b/cmake/FindUV.cmake
@@ -1,16 +1,5 @@
-find_path(
-    UV_INCLUDE_DIR
-    NAMES uv.h
-    PATHS "${XMRIG_DEPS}" ENV "XMRIG_DEPS"
-    PATH_SUFFIXES "include"
-)
-
-find_library(
-    UV_LIBRARY
-    NAMES libuv.a uv libuv
-    PATHS "${XMRIG_DEPS}" ENV "XMRIG_DEPS"
-    PATH_SUFFIXES "lib"
-)
+find_path(UV_INCLUDE_DIR NAMES uv.h)
+find_library(UV_LIBRARY NAMES uv libuv)
 
 set(UV_LIBRARIES ${UV_LIBRARY})
 set(UV_INCLUDE_DIRS ${UV_INCLUDE_DIR})
```

I've further reduced this for the current master (efa21b2531291ce957a9c7e8b65be81a1278bfe5), and this patch seems to resolve the problem:
```
diff --git a/cmake/FindUV.cmake b/cmake/FindUV.cmake
index ba59d1d..cd78c17 100644
--- a/cmake/FindUV.cmake
+++ b/cmake/FindUV.cmake
@@ -16,7 +16,7 @@ find_library(
     NO_DEFAULT_PATH
 )
 
-find_library(UV_LIBRARY NAMES libuv.a uv libuv)
+find_library(UV_LIBRARY NAMES uv libuv)
 
 set(UV_LIBRARIES ${UV_LIBRARY})
 set(UV_INCLUDE_DIRS ${UV_INCLUDE_DIR})
```

@xmrig I'm not sure if this patch is ok to PR or if this breaks anything. I assume the instructions in #238 are currently defunct as well. Advice would be appreciated.

**Comment by xmrig** [comment]
Please show cmake output with current master and after your changes, interesting line is `Found UV` it show what exactly library used in both cases.
Thank you.

**Comment by kpcyrd** [comment]
The `Found UV` line differs:

master: `-- Found UV: /usr/lib/libuv.a` (non static)
patched: `-- Found UV: /usr/lib/libuv.so` (static)

### Full output

#### Current master:
```
/xmrig/build # cmake .. -DWITH_HTTPD=OFF -DBUILD_STATIC=ON
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/libuv.a  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /xmrig/build
/xmrig/build # make
Scanning dependencies of target cpuid
[  2%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[  4%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[  6%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[  8%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 10%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
[ 13%] Linking C static library libcpuid.a
[ 13%] Built target cpuid
Scanning dependencies of target xmrig
[ 15%] Building CXX object CMakeFiles/xmrig.dir/src/api/Api.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig.dir/src/api/NetworkState.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig.dir/src/App.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig.dir/src/Console.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig.dir/src/log/ConsoleLog.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig.dir/src/log/FileLog.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig.dir/src/log/Log.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig.dir/src/Mem.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig.dir/src/net/Client.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig.dir/src/net/Job.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig.dir/src/net/Network.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig.dir/src/net/strategies/DonateStrategy.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig.dir/src/net/SubmitResult.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig.dir/src/net/Url.cpp.o
[ 52%] Building CXX object CMakeFiles/xmrig.dir/src/Options.cpp.o
[ 54%] Building CXX object CMakeFiles/xmrig.dir/src/Platform.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig.dir/src/Summary.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig.dir/src/workers/DoubleWorker.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Handle.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Hashrate.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig.dir/src/workers/SingleWorker.cpp.o
[ 67%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Worker.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Workers.cpp.o
[ 71%] Building CXX object CMakeFiles/xmrig.dir/src/xmrig.cpp.o
[ 73%] Building CXX object CMakeFiles/xmrig.dir/src/App_unix.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrig.dir/src/Cpu_unix.cpp.o
[ 78%] Building CXX object CMakeFiles/xmrig.dir/src/Mem_unix.cpp.o
[ 80%] Building CXX object CMakeFiles/xmrig.dir/src/Platform_unix.cpp.o
[ 82%] Building CXX object CMakeFiles/xmrig.dir/src/Cpu.cpp.o
[ 84%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_keccak.c.o
[ 86%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_groestl.c.o
[ 89%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_blake256.c.o
[ 91%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_jh.c.o
[ 93%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_skein.c.o
[ 95%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/CryptoNight.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig.dir/src/log/SysLog.cpp.o
[100%] Linking CXX executable xmrig
[100%] Built target xmrig
/xmrig/build # ldd xmrig 
	ldd (0x697861259000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x697860c84000)
	libc.musl-x86_64.so.1 => ldd (0x697861259000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x697860a72000)
/xmrig/build # 
```
#### Patched:
```
/xmrig/build # cmake .. -DWITH_HTTPD=OFF -DBUILD_STATIC=ON
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/libuv.so  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /xmrig/build
/xmrig/build # make
Scanning dependencies of target cpuid
[  2%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[  4%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[  6%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[  8%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 10%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
[ 13%] Linking C static library libcpuid.a
[ 13%] Built target cpuid
Scanning dependencies of target xmrig
[ 15%] Building CXX object CMakeFiles/xmrig.dir/src/api/Api.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig.dir/src/api/NetworkState.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig.dir/src/App.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig.dir/src/Console.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig.dir/src/log/ConsoleLog.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig.dir/src/log/FileLog.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig.dir/src/log/Log.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig.dir/src/Mem.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig.dir/src/net/Client.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig.dir/src/net/Job.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig.dir/src/net/Network.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig.dir/src/net/strategies/DonateStrategy.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig.dir/src/net/SubmitResult.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig.dir/src/net/Url.cpp.o
[ 52%] Building CXX object CMakeFiles/xmrig.dir/src/Options.cpp.o
[ 54%] Building CXX object CMakeFiles/xmrig.dir/src/Platform.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig.dir/src/Summary.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig.dir/src/workers/DoubleWorker.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Handle.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Hashrate.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig.dir/src/workers/SingleWorker.cpp.o
[ 67%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Worker.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrig.dir/src/workers/Workers.cpp.o
[ 71%] Building CXX object CMakeFiles/xmrig.dir/src/xmrig.cpp.o
[ 73%] Building CXX object CMakeFiles/xmrig.dir/src/App_unix.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrig.dir/src/Cpu_unix.cpp.o
[ 78%] Building CXX object CMakeFiles/xmrig.dir/src/Mem_unix.cpp.o
[ 80%] Building CXX object CMakeFiles/xmrig.dir/src/Platform_unix.cpp.o
[ 82%] Building CXX object CMakeFiles/xmrig.dir/src/Cpu.cpp.o
[ 84%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_keccak.c.o
[ 86%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_groestl.c.o
[ 89%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_blake256.c.o
[ 91%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_jh.c.o
[ 93%] Building C object CMakeFiles/xmrig.dir/src/crypto/c_skein.c.o
[ 95%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/CryptoNight.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig.dir/src/log/SysLog.cpp.o
[100%] Linking CXX executable xmrig
[100%] Built target xmrig
/xmrig/build # ldd xmrig 
	ldd (0x6a105e579000)
/xmrig/build # 
```

**Comment by xmrig** [comment]
Okay thank you for feedback, it confusing libuv.a should be static and libuv.so dynamic, I will better check your case latter. Also you can explicitly specify path to libuv like this: `cmake .. -DWITH_HTTPD=OFF -DBUILD_STATIC=ON -DUV_LIBRARY=/usr/lib/libuv.so`

**Comment by qusstem** [comment]
i'm build on ubuntu libuv version 1.18.0 with 
`/configure LDFLAGS="-static" `
after i make deb package and install after i build xmrig with 
`cmake .. -DWITH_HTTPD=OFF  -DBUILD_STATIC=ON`

and i have xmrig static 

```
xmrig-2.6.0-beta2/123$ ldd xmrig 
	not a dynamic executable
```
gcc ver 5.4
libuv 1.18.0 created deb package 


P.S. Sorry for my english.

**Pull request merged**
