### PR TITLE
Cryptonight variant 2 support

### PR DESCRIPTION
**Pull request by SChernykh**
Reference code is here: https://github.com/monero-project/monero/pull/4218
I've tested this on x86-64 and ARM for all possible combinations of "algo" and "av" parameters in config.json and it passed self-tests. Performance for variants 0&1 didn't change, compiler even generates the same assembly code (except it uses different registers). Performance for variant 2 is the same as in my repository for tests and benchmarks.

### CODE REVIEW

**Comment by xmrig** [comment]
Thank you for pull request. Is any test pool available right now?

**Comment by SChernykh** [comment]
There is no test pool now because Monero's PR is not merged yet. It should be merged this week (hopefully) and then Monero's testnet will switch to variant 2.

**Comment by xmrig** [comment]
I merge your commits into [feature-cn-variant2](https://github.com/xmrig/xmrig/commits/feature-cn-variant2) branch and will create same branches for other projects.

I added 32 bit support for x86 also I got invalid hashes on MSYS2 gcc 7.1 (lazy to update it on my dev machine) https://github.com/xmrig/xmrig/commit/075565e6fa4f346c90ef6cb02028d52ab6363a64 but gcc 7.2+ works fine, it might be my local issue, need additional checks.
Thank you.

**Comment by SChernykh** [comment]
Yes, this subborrow/addcarry bug was probably only fixed in gcc 7.2

**Comment by 2010phenix** [comment]
@xmrig Hi.
if monero move to variant 2 maybe need and for classic miner some love? maybe remove variant 0..
I can test when be test pool

**Comment by xmrig** [comment]
@2010phenix sure.

**Comment by 2010phenix** [comment]
Thx @xmrig.
I think we have some data for v8 already: https://github.com/monero-project/monero/pull/4358/commits/7f590e72619e81b943af9ad48858472ea78c0918

**Comment by xmrig** [comment]
Merged, all new information/discussion will be placed there #753

**Pull request merged**
