### PR TITLE
Self select with origin submit

### PR DESCRIPTION
**Pull request by hansieodendaal**
**Allow result submission to origin daemon with self-select**
(_Please see discussion in #2040_).

With `self-select` mode enabled, the `submit-to-origin` config option will let the `SelfSelectClient` submit the solution to both the origin daemon where it got the template from as well as to the connected pool.
Submission to the origin daemon will only be done if achieved difficulty is equal to or higher than the target difficulty received with the block template.

This will enable pool mining for Monero in conjunction with solo merged mining with an altcoin.

Thank you and special credit to @StriderDM (https://github.com/StriderDM)!

------------------------------------

This version of XMRig has been tested in conjunction with [Tari merge mining](https://github.com/tari-project/tari/blob/development/README.md#tari-merge-mining) and Monero mainnet.

Example config.json file:
```
{
    "autosave": true,
    "cpu": true,
    "opencl": false,
    "cuda": false,
    "pools": [
        {
            "coin": "monero",
            "algo": "rx/0",
            "url": "cryptonote.social:5555",
            "user": "<wallet address>.<handle at cryptonote.social>",
            "pass": "start_diff=100000;payment_scheme=pprop;donate=0.5",
            "tls": false,
            "keepalive": true,
            "nicehash": false,
            "self-select": "127.0.0.1:7878",
            "submit-to-origin": true
        }
    ]
}
```

Example console output:
``` rust
 * ABOUT        XMRig/6.7.3-dev MSVC/2019
 * LIBS         libuv/1.40.0 OpenSSL/1.1.1h
 * HUGE PAGES   permission granted
 * 1GB PAGES    unavailable
 * CPU          Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (1) 64-bit AES VM
                threads:8
 * MEMORY       12.1/31.9 GB (38%)
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      cryptonote.social:5555 coin monero self-select 127.0.0.1:7878 submit-to-origin
 * COMMANDS     hashrate, pause, resume, results, connection
 * OPENCL       disabled
 * CUDA         disabled
[2021-01-18 11:40:32.206]  net      use pool cryptonote.social:5555  75.144.254.101
[2021-01-18 11:40:33.235]  net      new job from cryptonote.social:5555 diff 220006 algo rx/0 height 2277083
[2021-01-18 11:40:33.235]  cpu      use argon2 implementation AVX2
[2021-01-18 11:40:33.413]  msr      register values for "intel" preset has been set successfully (177 ms)
[2021-01-18 11:40:33.413]  randomx  init dataset algo rx/0 (8 threads) seed c16b9816e30cf2bc...
[2021-01-18 11:40:33.863]  randomx  allocated 2336 MB (2080+256) huge pages 100% 1168/1168 +JIT (450 ms)
[2021-01-18 11:40:38.199]  randomx  dataset ready (4336 ms)
[2021-01-18 11:40:38.200]  cpu      use profile  rx  (4 threads) scratchpad 2048 KB
[2021-01-18 11:40:38.262]  cpu      READY threads 4/4 (4) huge pages 100% 4/4 memory 8192 KB (62 ms)
[2021-01-18 11:40:48.392]  net      new job from cryptonote.social:5555 diff 220006 algo rx/0 height 2277084
[2021-01-18 11:41:22.378]  origin   submitted to origin daemon (1/0)  diff 284557 vs. 371742
[2021-01-18 11:41:22.812]  cpu      accepted (1/0) diff 220006 (433 ms)
[2021-01-18 11:41:39.201]  miner    speed 10s/60s/15m 1562.2 1630.4 n/a H/s max 1710.0 H/s
[2021-01-18 11:42:05.837]  origin   not submitted to origin daemon, difficulty too low (1/1)  diff 284557 vs. 230465
[2021-01-18 11:42:06.320]  cpu      accepted (2/0) diff 220006 (482 ms)
```

### CODE REVIEW

**Comment by delta1** [comment]
Nice!

**Comment by xmrig** [comment]
This PR merged into the dev branch, once I merge it into master branch this PR will be marked as merged automatically.
Thank you.

**Comment by xmrig** [comment]
[v6.9.0](https://github.com/xmrig/xmrig/releases/tag/v6.9.0) released. Good luck.

**Comment by delta1** [comment]
Thanks @xmrig 🙏

**Comment by hansieodendaal** [comment]
Awesome, thanks @xmrig !!

**Pull request merged**
