### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Snider**
Makes this easier to read for native english speakers.

### Before:
image

### After:
image

### CODE REVIEW

**Review by Titaniumtown — APPROVED** [review]
LGTM (I'm a native english speaker)

**Comment by Titaniumtown** [comment]
??

**Comment by xmrig** [comment]
Done https://github.com/xmrig/xmrig/commit/5bf90704a622b5071a17cb76c9e81b64dbcc13e9

Somehow missed this PR, also unable to merge it now since the parent repository is removed and this PR was created against the master branch.
Thank you.

**Comment by Snider** [comment]
Was cleaning up the namespace to be acceptable to all industries, I'll make another fork for anything else I spot.

You're welcome, thank you for the work you do.

**Pull request closed without merging**
