### PR TITLE
Add support for KangarooTwelve (Aeon v8)

### PR DESCRIPTION
**Pull request by stoffu**
Aeon is planning to change its PoW to KangarooTwelve (https://github.com/aeonix/aeon/pull/108) in the next v8 hard fork. This patch adds the most basic support for the algorithm where the reference code is simply copied. I don't think there's much point in trying to optimize the CPU code since CPUs seem to be easily overwhelmed by GPUs.

It is highly appreciated if you could implement the algorithm for your GPU miners.

### CODE REVIEW

**Comment by stoffu** [comment]
Testnet pool: http://162.210.173.150:8080/

**Comment by xmrig** [comment]
Any ETA for the fork?
Thank you.

**Comment by stoffu** [comment]
Though pure speculation, the reasonable time for the fork seems to be around mid May or early June.

**Comment by xmrig** [comment]
Okay, thank you for information and PRs, I now busy on miner refactoring (long way to xmrig3) seems enough time to do it without emergency releases.

**Comment by BigslimVdub** [comment]
@xmrig Were you still interested in "officially" adding Aeon to xmrig products or available to in the near future?

**Pull request closed without merging**
