### PR TITLE
Added support for IPBC

### PR DESCRIPTION
**Pull request by ipbc-dev**

### CODE REVIEW

**Comment by xmrig** [comment]
Looks like we done double work for CPU miner, I added IPBC support in `feature-algo` branch too https://github.com/xmrig/xmrig/commit/ba5f92c6dd07b1cdd9a21e74fbee563b6e5bf42d
I decided to leave the name of the algorithm unchanged, it will be `cryptonight-lite` variant `ipbc` or `cryptonight-ipbc/ipbc` or `cn-lite/ipbc`. So miner will able switch between all 3 variants in runtime. Anyway thank you for pull requests.

**Comment by armin884** [comment]
Does this work with xmrig-proxy? Always Low difficulty share error...

**Comment by ipbc-dev** [comment]
@xmrig Didn't notice the branch, oh well, you know your code better than I do so better that way. Yea it's definitely nice for the miner to be able to switch between variants on runtime.

@armin884 I haven't received any low difficulty shares while testing with xmrig-proxy and the CPU miner.

**Comment by armin884** [comment]
@ipbc-dev ipbc-miner-win64-cuda9-1.1.3 is working, but xmrig feature-algo branch didn't. May you can post a sample config with xmrig working

**Comment by xmrig** [comment]
@armin884 First you should set global algorithm `"algo": "cryptonight-lite",`
Then on each IPBC pool set `"variant": "ipbc"`.

Example:
```json
{
  "algo": "cryptonight-lite",
  "pools": [
      {
            "url": "support.ipbc.io:13333",
            "user": "b...",
            "pass": "w2",
            "keepalive": false,
            "nicehash": false,
            "variant": "ipbc"
      }
  ]
}
```

**Comment by 2010phenix** [comment]
@xmrig maybe need add aliase for compactable?
https://github.com/fireice-uk/xmr-stak/pull/1489

**Comment by xmrig** [comment]
@2010phenix proxy support xmr-stak alias when verify algorithms, but for miner it not suitable, because it spited to 2 parts base algorithm and variant. https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md

IPBC support for CPU miner added in v2.6.2.

**Pull request closed without merging**
